apiVersion: batch/v1
kind: Job
metadata:
  name: cassachange-cassandra
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: cassachange-cassandra
          image: PLACEHOLDER
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: cassandra-credentials
          volumeMounts:
            - name: cassachange-config
              mountPath: /migrations/cassachange.yml
              subPath: cassachange.yml
      volumes:
        - name: cassachange-config
          configMap:
            name: cassachange-config
